In [ ]:
'''Question 1:

Write a program that calculates and prints the value according to the given formula:

Q = Square root of [(2 * C * D)/H]

Following are the fixed values of C and H:

C is 50. H is 30.

D is the variable whose values should be input to your program in a comma-separated sequence.

Example

Let us assume the following comma separated input sequence is given to the program:

100,150,180

The output of the program should be:

18,22,24 '''


In [12]:
import math

c = 50
h = 30

d = input('enter values')
d = d.split(',')

for i in d:
  a = round(math.sqrt((2*c*int(i))/h),3)
  print(a)


enter values2,3,4
2.582
3.162
3.651


2.581988897471611


In [ ]:
'''
Question 2:
Write a program which takes 2 digits, X,Y as input and generates a 2-dimensional array. 
The element value in the i-th row and j-th column of the array should be i*j.

Note: i=0,1.., X-1; j=0,1,¡¬Y-1.

Example

Suppose the following inputs are given to the program:

3,5

Then, the output of the program should be:

[[0, 0, 0, 0, 0],
 [0, 1, 2, 3, 4],
 [0, 2, 4, 6, 8]] 

'''


In [14]:
import numpy as np

a = 3
b = 5
c = []

for i in range(a):
  d = []
  for j in range(b):
    d.append(i*j)
  c.append(d)


print(np.array(c))


[[0 0 0 0 0]
 [0 1 2 3 4]
 [0 2 4 6 8]]


In [ ]:

'''
Question 3:
Write a program that accepts a comma separated sequence of words as input and prints the words in a comma-separated sequence after sorting them alphabetically.

Suppose the following input is supplied to the program:

without,hello,bag,world

Then, the output should be:

bag,hello,without,world

'''


In [17]:
a = input('enter input words ...')

a = a.split(',')


print(sorted(a))

enter input words ...without,hello,bag,world
['bag', 'hello', 'without', 'world']


In [ ]:
'''

Question 4:
Write a program that accepts a sequence of whitespace separated words as input and prints the words after removing all duplicate words and sorting them alphanumerically.

Suppose the following input is supplied to the program:

hello world and practice makes perfect and hello world again

Then, the output should be:

again and hello makes perfect practice world '''



In [19]:
a = input('enter space seperated values...')

a = list(set(a.split()))

print(sorted(a))

enter space seperated values...hello world and practice makes perfect and hello world again
['again', 'and', 'hello', 'makes', 'perfect', 'practice', 'world']


In [ ]:
'''

Question 5:

Write a program that accepts a sentence and calculate the number of letters and digits.

Suppose the following input is supplied to the program:

hello world! 123

Then, the output should be:

LETTERS 10

DIGITS 3

'''


In [28]:
a = 'hello world! 123'
letters = 0
Digits = 0

for i in a:
  if i.isalpha():
    letters = letters+1
  if i.isnumeric():
    Digits = Digits+1

print(letters)
print(Digits)


10
3


In [ ]:
'''
Question 6:
A website requires the users to input username and password to register. Write a program to check the validity of password input by users.

Following are the criteria for checking the password:

1. At least 1 letter between [a-z]

2. At least 1 number between [0-9]

1. At least 1 letter between [A-Z]

3. At least 1 character from [$#@]

4. Minimum length of transaction password: 6

5. Maximum length of transaction password: 12

Your program should accept a sequence of comma separated passwords and will check them according to the above criteria. Passwords that match the criteria are to be printed, each separated by a comma.

Example

If the following passwords are given as input to the program:

ABd1234@1,a F1#,2w3E*,2We3345

Then, the output of the program should be:

ABd1234@1
 '''

In [34]:
import string
import re

a = input('enter pass word..')

x = True
b = string.punctuation

while x :
  if not 6<len(a) or len(a)>12 :
    print('its not valid password..')
    break
  elif not re.search('[a-z]',a) :
    print('its not valid password..')
    break
  elif not re.search('[0-9]',a) :
    print('its not valid password..')
    break
  elif not re.search('[A-z]',a) :
    print('its not valid password...')
    break

  elif not re.search('[$#@]',a):
    print('its not valid password...')
    break

  else :
    print('valid password..')
    x = False
    break

if x :
  print('Not a valid Password...')



enter pass word..Siva@1234
valid password..
