In [10]:
# 1.	Write a Python Program to Add Two Matrices?

import numpy as np

l = [1,2]
l1 = [2,3]

l = np.array(l)
l1 = np.array(l1)

print((l+l1))

[3 5]


In [11]:
# 2.	Write a Python Program to Multiply Two Matrices?

l = [1,2]
l1 = [2,3]

l = np.array(l)
l1 = np.array(l1)

print(l*l1)

[2 6]


In [22]:
# 3.	Write a Python Program to Transpose a Matrix?

a = [[1,2,3],[4,5,6],[7,8,9]]

a = np.array(a)

print(a.T)

print(np.transpose(a))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [27]:
# 4.	Write a Python Program to Sort Words in Alphabetic Order?

a = 'i am siva durga prasad and i would like to becom an datascientist'

a = a.split()

print(a.sort())


None


In [19]:
# 5.	Write a Python Program to Remove Punctuation From a String?

import re

test_str = "Gfg, is best : for ! Geeks ;"


print("The original string is : " + test_str)


res = re.sub(r'[^\w\s]', '', test_str)

# printing result
print("The string after punctuation filter : " + res)


The original string is : Gfg, is best : for ! Geeks ;
The string after punctuation filter : Gfg is best  for  Geeks 
